global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s

  - job_name: 'restaurantiq-backend'
    static_configs:
      - targets: ['backend:3000']
    scrape_interval: 5s
    metrics_path: '/metrics'
    params:
      format: ['prometheus']
    http_config:
      headers:
        Accept: 'text/plain; version=0.0.4'

  - job_name: 'restaurantiq-frontend'
    static_configs:
      - targets: ['frontend:3001']
    scrape_interval: 30s
    metrics_path: '/api/metrics'
    params:
      format: ['prometheus']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    scrape_interval: 30s

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s

  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']
    scrape_interval: 30s
    metrics_path: '/nginx_status'
    params:
      format: ['prometheus']
