name: Setup Self-Hosted Runner
on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform'
        required: true
        default: 'setup'
        type: choice
        options:
          - setup
          - remove

jobs:
  setup-runner:
    runs-on: ubuntu-latest
    steps:
      - name: Setup self-hosted runner
        run: |
          # Download and setup GitHub Actions runner
          mkdir -p ./actions-runner
          cd ./actions-runner

          curl -o actions-runner-linux-arm64-2.311.0.tar.gz \
            -L https://github.com/actions/runner/releases/download/v2.311.0/actions-runner-linux-arm64-2.311.0.tar.gz

          tar xzf ./actions-runner-linux-arm64-2.311.0.tar.gz

          ./config.sh --url https://github.com/${{ github.repository }} \
                      --token ${{ secrets.RUNNER_TOKEN }} \
                      --name "restaurantiq-m4pro" \
                      --work _work \
                      --labels "self-hosted,macos,arm64" \
                      --unattended \
                      --replace

          ./run.sh &
